"""Initialize a new FORGE project."""

import os
import shutil
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.prompt import Confirm

console = Console()


def run_init(
    project_name: Optional[str] = None,
    integration: str = "copilot",
    force: bool = False,
) -> None:
    """Initialize a FORGE project directory."""
    if not project_name or project_name == ".":
        target_dir = Path.cwd()
    else:
        target_dir = Path.cwd() / project_name

    if target_dir.exists() and not force:
        if not Confirm.ask(f"Directory {target_dir} already exists. Continue?"):
            typer.Exit(code=1)
            return

    target_dir.mkdir(parents=True, exist_ok=True)

    forge_dir = target_dir / ".forge"
    forge_dir.mkdir(parents=True, exist_ok=True)

    # Create FORGE directory structure
    subdirs = [
        "signals",
        "hypotheses",
        "decisions",
        "features",
        "experiments",
        "releases",
        "retrospectives",
        "cognitive-contracts",
        "memory",
        "templates",
        "templates/overrides",
        "templates/commands",
        "scripts/bash",
        "scripts/powershell",
        "graph",
        "ai/cache",
    ]

    for subdir in subdirs:
        (forge_dir / subdir).mkdir(parents=True, exist_ok=True)

    # Create initial forge config
    config_path = forge_dir / "forge.config.yaml"
    if not config_path.exists() or force:
        _write_config(config_path)

    # Reference the FORGE methodology
    memory_dir = forge_dir / "memory"
    constitution_path = memory_dir / "constitution.md"
    if not constitution_path.exists() or force:
        _write_constitution(constitution_path)

    # Create VSCode settings
    vscode_dir = target_dir / ".vscode"
    vscode_dir.mkdir(exist_ok=True)
    settings_path = vscode_dir / "settings.json"
    if not settings_path.exists() or force:
        _write_vscode_settings(settings_path)

    console.print("[bold green]✅ FORGE project initialized![/bold green]")
    console.print(f"  📁 {target_dir}")
    console.print(f"  🔧 Integration: {integration}")
    console.print(f"\nNext steps:")
    console.print(f"  1. cd {target_dir.name}")
    console.print(f"  2. /forge.signal — Capture your first signal")
    console.print(f"  3. /forge.hypothesize — Form a hypothesis")


def _write_config(path: Path) -> None:
    """Write the FORGE configuration file."""
    config = """# .forge/forge.config.yaml
version: "1.0.0"
project:
  id: ""
  name: ""
  team: ""

staleness:
  signal_days: 90
  hypothesis_days: 30
  decision_days: 180
  feature_days: 45

drift:
  warning_threshold: 0.2
  critical_threshold: 0.4
  emergency_threshold: 0.6
  auto_escalation: true

governance:
  consent_timeout_hours: 48
  decision_types:
    architectural: [tech-lead, affected-team-leads]
    product: [product-lead, design-lead]
    operational: [team-lead]
    execution: [squad]

ai:
  auto_cluster_signals: true
  auto_draft_hypotheses: false
  confidence_threshold: 0.7

integrations:
  git:
    require_forge_links: true
  telemetry:
    provider: ""
"""
    path.write_text(config)


def _write_constitution(path: Path) -> None:
    """Write the FORGE constitution file."""
    constitution = """# [PROJECT] FORGE Constitution

## Article I: Signal-First
Every feature MUST start with a Signal. No feature shall be implemented without a traceable lineage to one or more signals.

## Article II: Hypothesis Framing
Every feature is a hypothesis, not a requirement.

## Article III: Consent Over Approval
Governance is consent-based, not approval-based.

## Article IV: Decisions Are Artifacts
Every significant choice is recorded as a Decision artifact.

## Article V: Unknowns Are First-Class
Every artifact MUST carry an unknowns field.

## Article VI: Drift Detection
Implementation drift from intent is continuously measured.

---
*Generated by Forge Kit. See forge-methodology.md for the complete methodology.*
"""
    path.write_text(constitution)


def _write_vscode_settings(path: Path) -> None:
    """Write VS Code settings for FORGE integration."""
    import json
    settings = {
        "forge.enabled": True,
        "forge.linting": {
            "decision_violations": "error",
            "missing_forge_link": "warning",
            "stale_ac_reference": "warning",
        },
        "forge.inline_annotations": {
            "show_drift_score": True,
            "show_linked_hypothesis": True,
        },
    }
    # Merge with existing if present
    if path.exists():
        try:
            existing = json.loads(path.read_text())
            existing.update(settings)
            settings = existing
        except Exception:
            pass
    path.write_text(json.dumps(settings, indent=2))
